apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo
  namespace: flask-todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
        - name: flask
          image: zahidbilal/flask-argcdimageupdater:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
