apiVersion: v1
kind: Service
metadata:
  name: flask-todo
  namespace: flask-todoapp
spec:
  selector:
    app: flask-todo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
